### ISSUE TITLE
Add Ability to Override Network Test IP

### ISSUE THREAD

**Issue by SuperJC710e** [Romanitho/Winget-AutoUpdate#120]
Thanks for this awesome tool!

On my network, we have all DNS IPs blocked, except a specific set. One of the blocked ones happens to be `8.8.8.8`, the very one used to test for network connectivity. 

**Winget-AutoUpdate\functions\Test-Network.ps1**

`$TestNetwork = Test-NetConnection 8.8.8.8 -Port 443 -InformationLevel Quiet`

Is there a way we can override that, perhaps with a parameter or a config. Or perhaps we could have a set of IPs to check? Or even an override to bypass the network check?

TIA

**Comment by Romanitho** [comment]
Hi,
Yes, that's good ideas. If you don't use the WAU Self Update feature, feel free to custom the scripts on your deployments.
I need to change that anyway, because my first approach was to have a test even if you are connected behind a captive portal (on wifi for instance). My idea was to have a test that can wait until there is a real connection.
Basically, test connectivity based on URL would success behind a captive portal due to redirections...

Thanks for your comment and Help :)
