### ISSUE TITLE
Applications in use

### ISSUE THREAD

**Issue by hennibadger16** [Romanitho/Winget-AutoUpdate#128]
Hi,

as I don't find the time to test it myself right now I hoped somebody might help me out here:

If using WAU and trying to update apps on user logon: What happens to apps actively in use? (Consider locked screen or a really fast user :))

Are they skipped from updating or force closed and updated? How would you go about tackling possible "data / work loss"?
(If that's a real problem - maybe even worth to add a CLI flag to skip running apps?)

Your help is much appreciated.

Great work :)

**Comment by Romanitho** [comment]
Hi.
As we've just created a script to better handle Winget Updates, we still use Winget engine itself and we are based on Winget mechanisms. So it really depends on how Winget (or the apps themself) handle running apps.
We hope to have a better control in next Winget releases that we can exploit with WAU to give a better control on the behavior you want to have when using our script :)

**Comment by hennibadger16** [comment]
> Hi. As we've just created a script to better handle Winget Updates, we still use Winget engine itself and we are based on Winget mechanisms. So it really depends on how Winget (or the apps themself) handle running apps. We hope to have a better control in next Winget releases that we can exploit with WAU to give a better control on the behavior you want to have when using our script :)

Oh I see - thank you very much.
Based on your experience: Is it a problematic real world scenario or do Winget / most applications handle those upgrades just fine? I guess you've got a whole lot more experience in it :). If it's mostly neglectable I guess I would try to find some time for a proof of concept and staged rollout. If not I might just wait for future developments.

Much appreciated :)

**Comment by Romanitho** [comment]
Regarding my own experience, it works great for most of apps. I only have trouble with apps like ShareX that start with Windows, so obviously if installer does't handle running apps, it can cause failure.
That's why we have Black list or White list system. Some of my customers use White list to run WAU only on known app list, others use black list to block known problematic apps 😊

For my personal use case, I have a block list with few apps like Office and browsers that can auto-update. For ShareX for instance, we hope dev (or winget) will handle that king of scenario soon 😅 but I don't put it in my block list, this way I'm aware of new available version (even if it fails)

Hope I am clear enough
