### ISSUE TITLE
Mods Request 

### ISSUE THREAD

**Issue by temeyers** [Romanitho/Winget-AutoUpdate#133]
Is there a way to trigger mods prior to the execution ?

the though process here is to pop a toast notification for some applications prior to install to allow the user to delay the install.

**Comment by KnifMelti** [comment]
Hello @temeyers!
The custom (**mods**) feature is somewhat my responsibility/idea so I'm writing this first reply.
The foremost use of it is via https://github.com/Romanitho/Winget-Install and it can be used to run your own powershell scripts placed in the **mods** folder (AppId + "-install-once", "-install" or "-uninstall")
It doesn't integrate in the installation/uninstallation at all but waits until the installation/upgrade have been marked successful.
The reason it is integrated in **WAU** is because some standard **upgrades** overwrites the modifications done (reg/file) for an application.

This proposal of yours could be an integration of some sort of delay/cancel of the installations in the **WAU toast notification** itself, and that's another thing (if your showing the notifications for the users)!

**Comment by KnifMelti** [comment]
The custom (**mods**) feature could be expanded to include "**-pre**" and "**-post**" scripts too **but** one problem is that when the upgrade loop in **WAU** runs you cant pause the script (running in System context) and show something for the user to respond to.
And a delay in that place would stop the loop from continuing the foreach looping through all the applications in need of an update...
