### ISSUE TITLE
Ability to specify version in included_apps.txt

### ISSUE THREAD

**Issue by MarkHowe86** [Romanitho/Winget-AutoUpdate#152]
The ability to specify a specific version in the included_apps.txt file for version control.

You can run the command from cmd "winget upgrade *AppName* --version 0.1.2" to only upgrade to that version, but when using the included_apps.txt with a version specified this does not work.

**Comment by Romanitho** [comment]
the upgrade to a specific version is not supported because you need to maintain the White/Black list file. so it's easier to maintain the app itself. the main idea here is to keep apps up to date.
In the future we will continue to improve these scripts and in a V2 we will probably extend the functionalities.
