### ISSUE TITLE
VC_redist vs VCLibs

### ISSUE THREAD

**Issue by gabriel-vanca** [Romanitho/Winget-AutoUpdate#381]
WinGet required either VC_redist or VCLibs in order to function.
Right now, the installer checks if VC_redist is present. As it happens, if VCLibs is installed, the VC_redist will still come as positive.
However, should it not check for both?

And should it not install VCLibs rather than VC_redist? VCLibs uses fewer resources from what I can tell and the install file is smaller too (6MB vs 26MB). Also, VCLibs needs to be installed anyway for apps such as Windows Terminal etc and already comes pre-installed on Windows 11.

Also, it's easier to check if VCLibs is present:

```
[String]$VersionToLookFor = "14.0.30704.0"
$vclibsList = Get-AppxPackage Microsoft.VCLibs.140.00.UWPDesktop | Where-Object version -ge $VersionToLookFor
    if([string]::IsNullorEmpty($vclibsList)) {
        Write-Host "Microsoft.VCLibs.140.00.UWPDesktop missing" -ForegroundColor DarkRed
    } else {
        Write-Host "The installed version of Microsoft.VCLibs.140.00.UWPDesktop is the same or newer as the version we are looking for." -ForegroundColor DarkGreen
    }
```

The WinGet chocolatey install seems to prefer installing VCLibs rather than VCredist.

I've not marked this as either a bug or a feature, as it's more of a discussion/something requiring investigation.

**Comment by AndrewDemski-ad-gmail-com** [comment]
Hi,
if runtime libraries cannot be found in one of appx containers, then logic applied seeks those "under the hood", in the system.
Just like the AppV used to do.

There are thousands of apps which have those VC 14.x as dependencies and most likely those will be more common in legacy state rather than as appx package.
Finding worth noting, when winget USES those files during its operation, it is automatically blocks those files from being upgraded.
Personally I am a big fan of msi-way of dealing with the flle replacement carried-out across reboot. 
That way winget will be less suscepptable to any errors caused by failed VC updates (yes,  I am a pessimist).
That is why I vote for VC_redist over VCLibs.
BR
Andrew
