### ISSUE TITLE
Add option "Run with highest Privileges in User-Context Task"

### ISSUE THREAD

**Issue by sis032** [Romanitho/Winget-AutoUpdate#474]
### The request

Hi.
Please add the option "Run with highest Privileges in User-Context Task."
We use it in our company, and our employees get scared when they try to ask them for additional rights during installation.
![image](https://github.com/Romanitho/Winget-AutoUpdate/assets/107427589/22e0e724-b0c6-4b63-96c8-0a9d1bcfddef)

**Comment by Romanitho** [comment]
This project uses system context to update apps that required privileges.
If your users don't have admin rights, the "Run with highest privileges" will prompt UAC anyway

**Comment by mtengmo** [comment]
> This project uses system context to update apps that required privileges. If your users don't have admin rights, the "Run with highest privileges" will prompt UAC anyway

So better to only include apps that don´t trigger UAC prompts?

**Comment by Romanitho** [comment]
WAU uses system context to update apps with admin right without prompting anything to standard users. Not sure to understand the problem here.

**Comment by KnifMelti** [comment]
Ciscos installer is only Scope: machine and the downloaded MSI is only installable by admins/System
https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Cisco/CiscoWebexMeetings

**Comment by mtengmo** [comment]
Cisco Webex is executed in my usercontext, that´s the strange thing. 

################################################################
#     3/13/2024 - CHECK FOR APP UPDATES (User context)
################################################################
19:12:03 - Notification Level: None. Notification Language: English
19:12:03 - Checking internet connection...
19:12:03 - Connected !
19:12:03 - Winget Version: v1.7.10582
19:12:03 - WAU current version: 1.19.2-10
19:12:03 - WAU uses White List config
19:12:03 - Checking application updates on Winget Repository...
-> Available update : Dev Home. Current version : 0.0.0.0. Available version : 0.1101.416.0.
-> Available update : Python 3.12.0 (64-bit). Current version : 3.12.0. Available version : 3.12.2.
-> Available update : Cisco Webex Meetings. Current version : 43.6.6. Available version : 44.2.1.6.
-> Available update : Microsoft Teams. Current version : 1.6.00.18681. Available version : 1.7.00.6058.
-> Available update : Windows Package Manager Manifest Creator. Current version : 1.1.2.0. Available version : 1.6.1.0.
19:12:07 - Dev Home : Skipped upgrade because it is not in the included app list
19:12:07 - Python 3.12.0 (64-bit) : Skipped upgrade because it is not in the included app list
19:12:08 - Updating Cisco Webex Meetings from 43.6.6 to 44.2.1.6...
19:12:09 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Cisco.CiscoWebexMeetings'   ##########
19:12:09 - -> Running: Winget upgrade --id Cisco.CiscoWebexMeetings -e --accept-package-agreements --accept-source-agreements -s winget -h

No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.
19:12:21 - -> An upgrade for Cisco Webex Meetings failed, now trying an install instead... (1/2)
19:12:22 - -> Running: Winget install --id Cisco.CiscoWebexMeetings -e --accept-package-agreements --accept-source-agreements -s winget -h --force
Found Cisco Webex Meetings [Cisco.CiscoWebexMeetings] Version 44.2.1.6
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://akamaicdn.webex.com/client/webexapp.msi

Successfully verified installer hash
Starting package install...

You cancelled the installation.
Installer failed with exit code: 1602
Installer log is available at: C:\Users\mteo\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Cisco.CiscoWebexMeetings.44.2.1.6-2024-03-13-19-13-46.380.log
19:14:13 - -> An upgrade for Cisco Webex Meetings failed, now trying an install instead... (2/2)
19:14:13 - -> Running: Winget install --id Cisco.CiscoWebexMeetings -e --accept-package-agreements --accept-source-agreements -s winget -h --force

Found Cisco Webex Meetings [Cisco.CiscoWebexMeetings] Version 44.2.1.6
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...

You cancelled the installation.
Installer failed with exit code: 1602
Installer log is available at: C:\Users\mteo\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Cisco.CiscoWebexMeetings.44.2.1.6-2024-03-13-19-14-15.372.log
19:15:17 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Cisco.CiscoWebexMeetings'   ##########
19:15:17 - Cisco Webex Meetings update failed.
19:15:17 - Microsoft Teams : Skipped upgrade because it is not in the included app list
19:15:17 - Windows Package Manager Manifest Creator : Skipped upgrade because it is not in the included app list
19:15:17 - No new update.
19:15:17 - End of process!

(I didn´t approved UAC here)

**Comment by AndrewDemski-ad-gmail-com** [comment]
Hi, quick check on winget repo:

https://github.com/microsoft/winget-pkgs/blob/0d9731c08457b70dfa688bfb5a58916c6863d7ce/manifests/c/Cisco/CiscoWebexMeetings/44.2.1.6/Cisco.CiscoWebexMeetings.installer.yaml#L9-L10
```
InstallerType: msi
Scope: machine
```
I could guestimate that some indicators of that product were detected in user context and that initiated an upgrade attempt.
I would not be surprised by the questionable level of quality presented by the Cisco team in the use of MSI package management standards.
As they say, the devil is in the details.
Most likely, the actual cause can be found in the LOG file: `C:\Users\mteo\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Cisco.CiscoWebexMeetings.44.2.1.6-2024-03-13-19-13-46.380.log`
