### ISSUE TITLE
[Bug]: Notion updates all the time

### ISSUE THREAD

**Issue by gabriel-vanca** [Romanitho/Winget-AutoUpdate#553]
### The problem

Notion keeps getting updated at every run.
It's always from version 2.0.47 to 3.1.1 or 2.0.49 to 3.1.1 . It always cycles between these.

Seeing that Notion updates itself automatically when it starts, if the issue can't be fixed, the app might need to be blacklisted.

### What version of WAU has the issue?

latest

### What version of Windows are you using (ex. Windows 11 22H2)?

11 22H2

### What version of winget are you using?

1.6.3482

**Comment by Romanitho** [comment]
This happen to me on some of apps that cannot "replace" themselves. This results with both apps in 2 versions... due to the "old" version WAU tries to update and succeed... but on next run, detected the old etc etc... and loop.
So in that case, i manually remove the old app each time it updates. (blacklist can be the solution, as your app autoupdate itself)
