### ISSUE TITLE
[Bug]: WAU tries to update packages which shouldn't be updated when sideBySide is enabled

### ISSUE THREAD

**Issue by soredake** [Romanitho/Winget-AutoUpdate#639]
### The problem

WAU tries to update packages like `Microsoft.DotNet.DesktopRuntime.8` / `Microsoft.XNARedist` even when it's not needed when sideBySide feature is enabled:
```
################################################################
#     6/6/2024 - CHECK FOR APP UPDATES (System context - Connected user)
################################################################
12:37:37 - Notification Level: Full. Notification Language: Русский
12:37:37 - Checking internet connection...
12:37:38 - Connected !
12:37:38 - Winget Version: v1.9.1551-preview
12:37:38 - WAU current version: 1.20.2-0
12:37:38 - WAU AutoUpdate is Enabled.
12:37:38 - WAU AutoUpdate Pre-release versions is Enabled
12:37:40 - WAU is up to date.
12:37:40 - WAU uses Black List config
12:37:40 - Checking application updates on Winget Repository...
-> Available update : Multipass. Current version : 1.12.2+win. Available version : 1.13.1.
-> Available update : Microsoft Windows Desktop Runtime - 6.0.31 (x86). Current version : < 8.0.0. Available version : 8.0.6.
-> Available update : SteelSeries GG 61.0.0. Current version : 61.0.0. Available version : 63.0.0.
-> Available update : Ubisoft Connect. Current version : 151.2.11050. Available version : 153.1.0.11069.
-> Available update : Microsoft Windows Desktop Runtime - 6.0.31 (x64). Current version : < 8.0.0. Available version : 8.0.6.
-> Available update : Microsoft XNA Framework Redistributable 3.1. Current version : 3.1.10527.0. Available version : 4.0.30901.0.
-> Available update : FileBot. Current version : 4.9.6. Available version : 5.1.3.
-> Available update : Parsec. Current version : 150-90d. Available version : 150.93.2.0.
-> Available update : Oracle VM VirtualBox 7.0.16. Current version : 7.0.16. Available version : 7.0.18.
-> Available update : EA app. Current version : 13.202.0.5715. Available version : 13.218.0.5731.
-> Available update : Dokan Library 1.0.5.1000 Bundle. Current version : 1.0.5.1000. Available version : 2.1.0.1000.
12:37:43 - Multipass : Skipped upgrade because it is in the excluded app list
12:37:44 - Updating Microsoft Windows Desktop Runtime - 6.0.31 (x86) from < 8.0.0 to 8.0.6...
12:37:48 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:37:48 - -> Running: Winget upgrade --id Microsoft.DotNet.DesktopRuntime.8 -e --accept-package-agreements --accept-source-agreements -s winget -h


  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 10.9 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 10.9 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 10.9 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 10.9 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 10.9 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 10.9 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 10.9 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 10.9 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 10.9 MB
  ███████████████████████████▒▒▒  10.0 MB / 10.9 MB
  ██████████████████████████████  10.9 MB / 10.9 MB

No installed package found matching input criteria.
12:37:52 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:37:52 - Microsoft Windows Desktop Runtime - 6.0.31 (x86) updated to 8.0.6 !
12:37:56 - SteelSeries GG 61.0.0 : Skipped upgrade because it is in the excluded app list
12:37:56 - Ubisoft Connect : Skipped upgrade because it is in the excluded app list
12:37:57 - Updating Microsoft Windows Desktop Runtime - 6.0.31 (x64) from < 8.0.0 to 8.0.6...
12:38:01 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:38:01 - -> Running: Winget upgrade --id Microsoft.DotNet.DesktopRuntime.8 -e --accept-package-agreements --accept-source-agreements -s winget -h


  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 10.9 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 10.9 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 10.9 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 10.9 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 10.9 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 10.9 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 10.9 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 10.9 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 10.9 MB
  ███████████████████████████▒▒▒  10.0 MB / 10.9 MB
  ██████████████████████████████  10.9 MB / 10.9 MB

No installed package found matching input criteria.
12:38:05 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:38:05 - Microsoft Windows Desktop Runtime - 6.0.31 (x64) updated to 8.0.6 !
12:38:10 - Updating Microsoft XNA Framework Redistributable 3.1 from 3.1.10527.0 to 4.0.30901.0...
12:38:14 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.XNARedist'   ##########
12:38:14 - -> Running: Winget upgrade --id Microsoft.XNARedist -e --accept-package-agreements --accept-source-agreements -s winget -h


  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 10.9 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 10.9 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 10.9 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 10.9 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 10.9 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 10.9 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 10.9 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 10.9 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 10.9 MB
  ███████████████████████████▒▒▒  10.0 MB / 10.9 MB
  ██████████████████████████████  10.9 MB / 10.9 MB

No available upgrade found.
No newer package versions are available from the configured sources.
12:38:18 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.XNARedist'   ##########
12:38:18 - Microsoft XNA Framework Redistributable 3.1 updated to 4.0.30901.0 !
12:38:22 - FileBot : Skipped upgrade because it is in the excluded app list
12:38:22 - Parsec : Skipped upgrade because it is in the excluded app list
12:38:22 - Oracle VM VirtualBox 7.0.16 : Skipped upgrade because it is in the excluded app list
12:38:22 - EA app : Skipped upgrade because it is in the excluded app list
12:38:22 - Dokan Library 1.0.5.1000 Bundle : Skipped upgrade because it is in the excluded app list
12:38:22 - 3 apps updated ! No more update.
12:38:23 - User logged on, get a list of installed Winget apps in System context...
12:38:26 - Starting WAU in User context...
```

Available updated with sideBySide feature disabled:
```
❯ sudo { winget list --upgrade-available  --include-unknown --scope=machine }
Имя                                              ИД                                Версия            Доступно             Источник
----------------------------------------------------------------------------------------------------------------------------------
DS4Windows                                       Ryochan7.DS4Windows               Unknown           3.3.3                winget
Microsoft Teams                                  Microsoft.Teams.Free              24047.202.2704.38 24124.2402.2858.5617 winget
Multipass                                        Canonical.Multipass               1.12.2+win        1.13.1               winget
Parsec                                           Parsec.Parsec                     150-90d           150.93.2.0           winget
SteelSeries GG 61.0.0                            SteelSeries.GG                    61.0.0            63.0.0               winget
Ubisoft Connect                                  Ubisoft.Connect                   151.2.11050       153.1.0.11069        winget
Microsoft XNA Framework Redistributable 3.1      Microsoft.XNARedist               3.1.10527.0       4.0.30901.0          winget
Microsoft Windows Desktop Runtime - 6.0.31 (x64) Microsoft.DotNet.DesktopRuntime.8 < 8.0.0           8.0.6                winget
Dokan Library 1.0.5.1000 Bundle                  dokan-dev.Dokany                  1.0.5.1000        2.1.0.1000           winget
Viber                                            XPFM5P5KDWF0JP                    21.6.0.0          22.8.0.0             msstore
EA app                                           ElectronicArts.EADesktop          13.202.0.5715     13.218.0.5731        winget
FileBot                                          PointPlanck.FileBot               4.9.6             5.1.3                winget
Oracle VM VirtualBox 7.0.16                      Oracle.VirtualBox                 7.0.16            7.0.18               winget
Microsoft Windows Desktop Runtime - 6.0.31 (x86) Microsoft.DotNet.DesktopRuntime.8 < 8.0.0           8.0.6                winget
Доступны обновления: 14.
```

Available updated with sideBySide feature enabled:
```
❯ sudo { winget list --upgrade-available  --include-unknown --scope=machine }
Имя                         ИД                       Версия            Доступно             Источник
----------------------------------------------------------------------------------------------------
DS4Windows                  Ryochan7.DS4Windows      Unknown           3.3.3                winget
SteelSeries GG 61.0.0       SteelSeries.GG           61.0.0            63.0.0               winget
FileBot                     PointPlanck.FileBot      4.9.6             5.1.3                winget
Oracle VM VirtualBox 7.0.16 Oracle.VirtualBox        7.0.16            7.0.18               winget
Multipass                   Canonical.Multipass      1.12.2+win        1.13.1               winget
Parsec                      Parsec.Parsec            150-90d           150.93.2.0           winget
Ubisoft Connect             Ubisoft.Connect          151.2.11050       153.1.0.11069        winget
EA app                      ElectronicArts.EADesktop 13.202.0.5715     13.218.0.5731        winget
Microsoft Teams             Microsoft.Teams.Free     24047.202.2704.38 24124.2402.2858.5617 winget
Доступны обновления: 9.
```

### What version of WAU has the issue?

v1.20.2-0

### What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

### What version of winget are you using?

1.9.1551-preview

### Additional information

https://github.com/microsoft/winget-cli/discussions/4281

How to enable sideBySide feature:
https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#sidebyside

**Comment by AndrewDemski-ad-gmail-com** [comment]
Hey,
is it possible to recreate the same issue on non-preview version of winget?
________________________________
From: soredake ***@***.***>
Sent: 06 June 2024 13:35
To: Romanitho/Winget-AutoUpdate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Romanitho/Winget-AutoUpdate] [Bug]: WAU tries to update packages which shouldn't be updated when sideBySide is enabled (Issue #639)


The problem

WAU tries to update packages like Microsoft.DotNet.DesktopRuntime.8 / Microsoft.XNARedist even when it's not needed when sideBySide feature is enabled:

################################################################
#     6/6/2024 - CHECK FOR APP UPDATES (System context - Connected user)
################################################################
12:37:37 - Notification Level: Full. Notification Language: Русский
12:37:37 - Checking internet connection...
12:37:38 - Connected !
12:37:38 - Winget Version: v1.9.1551-preview
12:37:38 - WAU current version: 1.20.2-0
12:37:38 - WAU AutoUpdate is Enabled.
12:37:38 - WAU AutoUpdate Pre-release versions is Enabled
12:37:40 - WAU is up to date.
12:37:40 - WAU uses Black List config
12:37:40 - Checking application updates on Winget Repository...
-> Available update : Multipass. Current version : 1.12.2+win. Available version : 1.13.1.
-> Available update : Microsoft Windows Desktop Runtime - 6.0.31 (x86). Current version : < 8.0.0. Available version : 8.0.6.
-> Available update : SteelSeries GG 61.0.0. Current version : 61.0.0. Available version : 63.0.0.
-> Available update : Ubisoft Connect. Current version : 151.2.11050. Available version : 153.1.0.11069.
-> Available update : Microsoft Windows Desktop Runtime - 6.0.31 (x64). Current version : < 8.0.0. Available version : 8.0.6.
-> Available update : Microsoft XNA Framework Redistributable 3.1. Current version : 3.1.10527.0. Available version : 4.0.30901.0.
-> Available update : FileBot. Current version : 4.9.6. Available version : 5.1.3.
-> Available update : Parsec. Current version : 150-90d. Available version : 150.93.2.0.
-> Available update : Oracle VM VirtualBox 7.0.16. Current version : 7.0.16. Available version : 7.0.18.
-> Available update : EA app. Current version : 13.202.0.5715. Available version : 13.218.0.5731.
-> Available update : Dokan Library 1.0.5.1000 Bundle. Current version : 1.0.5.1000. Available version : 2.1.0.1000.
12:37:43 - Multipass : Skipped upgrade because it is in the excluded app list
12:37:44 - Updating Microsoft Windows Desktop Runtime - 6.0.31 (x86) from < 8.0.0 to 8.0.6...
12:37:48 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:37:48 - -> Running: Winget upgrade --id Microsoft.DotNet.DesktopRuntime.8 -e --accept-package-agreements --accept-source-agreements -s winget -h


  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 10.9 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 10.9 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 10.9 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 10.9 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 10.9 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 10.9 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 10.9 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 10.9 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 10.9 MB
  ███████████████████████████▒▒▒  10.0 MB / 10.9 MB
  ██████████████████████████████  10.9 MB / 10.9 MB

No installed package found matching input criteria.
12:37:52 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:37:52 - Microsoft Windows Desktop Runtime - 6.0.31 (x86) updated to 8.0.6 !
12:37:56 - SteelSeries GG 61.0.0 : Skipped upgrade because it is in the excluded app list
12:37:56 - Ubisoft Connect : Skipped upgrade because it is in the excluded app list
12:37:57 - Updating Microsoft Windows Desktop Runtime - 6.0.31 (x64) from < 8.0.0 to 8.0.6...
12:38:01 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:38:01 - -> Running: Winget upgrade --id Microsoft.DotNet.DesktopRuntime.8 -e --accept-package-agreements --accept-source-agreements -s winget -h


  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 10.9 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 10.9 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 10.9 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 10.9 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 10.9 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 10.9 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 10.9 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 10.9 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 10.9 MB
  ███████████████████████████▒▒▒  10.0 MB / 10.9 MB
  ██████████████████████████████  10.9 MB / 10.9 MB

No installed package found matching input criteria.
12:38:05 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.DotNet.DesktopRuntime.8'   ##########
12:38:05 - Microsoft Windows Desktop Runtime - 6.0.31 (x64) updated to 8.0.6 !
12:38:10 - Updating Microsoft XNA Framework Redistributable 3.1 from 3.1.10527.0 to 4.0.30901.0...
12:38:14 - ##########   WINGET UPGRADE PROCESS STARTS FOR APPLICATION ID 'Microsoft.XNARedist'   ##########
12:38:14 - -> Running: Winget upgrade --id Microsoft.XNARedist -e --accept-package-agreements --accept-source-agreements -s winget -h


  ██▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 10.9 MB
  █████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 10.9 MB
  ████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 10.9 MB
  ██████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 10.9 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 10.9 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 10.9 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  7.00 MB / 10.9 MB
  █████████████████████▒▒▒▒▒▒▒▒▒  8.00 MB / 10.9 MB
  ████████████████████████▒▒▒▒▒▒  9.00 MB / 10.9 MB
  ███████████████████████████▒▒▒  10.0 MB / 10.9 MB
  ██████████████████████████████  10.9 MB / 10.9 MB

No available upgrade found.
No newer package versions are available from the configured sources.
12:38:18 - ##########   WINGET UPGRADE PROCESS FINISHED FOR APPLICATION ID 'Microsoft.XNARedist'   ##########
12:38:18 - Microsoft XNA Framework Redistributable 3.1 updated to 4.0.30901.0 !
12:38:22 - FileBot : Skipped upgrade because it is in the excluded app list
12:38:22 - Parsec : Skipped upgrade because it is in the excluded app list
12:38:22 - Oracle VM VirtualBox 7.0.16 : Skipped upgrade because it is in the excluded app list
12:38:22 - EA app : Skipped upgrade because it is in the excluded app list
12:38:22 - Dokan Library 1.0.5.1000 Bundle : Skipped upgrade because it is in the excluded app list
12:38:22 - 3 apps updated ! No more update.
12:38:23 - User logged on, get a list of installed Winget apps in System context...
12:38:26 - Starting WAU in User context...


Available updated with sideBySide feature disabled:

❯ sudo { winget list --upgrade-available  --include-unknown --scope=machine }
Имя                                              ИД                                Версия            Доступно             Источник
----------------------------------------------------------------------------------------------------------------------------------
DS4Windows                                       Ryochan7.DS4Windows               Unknown           3.3.3                winget
Microsoft Teams                                  Microsoft.Teams.Free              24047.202.2704.38 24124.2402.2858.5617 winget
Multipass                                        Canonical.Multipass               1.12.2+win        1.13.1               winget
Parsec                                           Parsec.Parsec                     150-90d           150.93.2.0           winget
SteelSeries GG 61.0.0                            SteelSeries.GG                    61.0.0            63.0.0               winget
Ubisoft Connect                                  Ubisoft.Connect                   151.2.11050       153.1.0.11069        winget
Microsoft XNA Framework Redistributable 3.1      Microsoft.XNARedist               3.1.10527.0       4.0.30901.0          winget
Microsoft Windows Desktop Runtime - 6.0.31 (x64) Microsoft.DotNet.DesktopRuntime.8 < 8.0.0           8.0.6                winget
Dokan Library 1.0.5.1000 Bundle                  dokan-dev.Dokany                  1.0.5.1000        2.1.0.1000           winget
Viber                                            XPFM5P5KDWF0JP                    21.6.0.0          22.8.0.0             msstore
EA app                                           ElectronicArts.EADesktop          13.202.0.5715     13.218.0.5731        winget
FileBot                                          PointPlanck.FileBot               4.9.6             5.1.3                winget
Oracle VM VirtualBox 7.0.16                      Oracle.VirtualBox                 7.0.16            7.0.18               winget
Microsoft Windows Desktop Runtime - 6.0.31 (x86) Microsoft.DotNet.DesktopRuntime.8 < 8.0.0           8.0.6                winget
Доступны обновления: 14.


Available updated with sideBySide feature enabled:

❯ sudo { winget list --upgrade-available  --include-unknown --scope=machine }
Имя                         ИД                       Версия            Доступно             Источник
----------------------------------------------------------------------------------------------------
DS4Windows                  Ryochan7.DS4Windows      Unknown           3.3.3                winget
SteelSeries GG 61.0.0       SteelSeries.GG           61.0.0            63.0.0               winget
FileBot                     PointPlanck.FileBot      4.9.6             5.1.3                winget
Oracle VM VirtualBox 7.0.16 Oracle.VirtualBox        7.0.16            7.0.18               winget
Multipass                   Canonical.Multipass      1.12.2+win        1.13.1               winget
Parsec                      Parsec.Parsec            150-90d           150.93.2.0           winget
Ubisoft Connect             Ubisoft.Connect          151.2.11050       153.1.0.11069        winget
EA app                      ElectronicArts.EADesktop 13.202.0.5715     13.218.0.5731        winget
Microsoft Teams             Microsoft.Teams.Free     24047.202.2704.38 24124.2402.2858.5617 winget
Доступны обновления: 9.


What version of WAU has the issue?

v1.20.2-0

What version of Windows are you using (ex. Windows 11 22H2)?

Windows 11 23H2

What version of winget are you using?

1.9.1551-preview

Log information

No response

Additional information

microsoft/winget-cli#4281<https://github.com/microsoft/winget-cli/discussions/4281>

How to enable sideBySide feature:
https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#sidebyside

**Comment by soredake** [comment]
@AndrewDemski-ad-gmail-com no, as stable version does not have experimental features
![изображение](https://github.com/Romanitho/Winget-AutoUpdate/assets/5204968/5340f1df-1666-4228-9e9e-8e93ec7bb3af)

**Comment by Romanitho** [comment]
WAU doesn't support winget in prerelease versions

**Comment by soredake** [comment]
Then let's wait for the stable version with this feature enabled, I think wau will still try to update those software unless something in code will change.

**Comment by Romanitho** [comment]
for me, apps in side by side should be excluded from WAU. We can maybe start to thing about how to handle that at the end.

**Comment by soredake** [comment]
Fixed with latest winget stable version.
