### ISSUE TITLE
[Feature Request]: Add "Mods"option to -NotificationLevel

### ISSUE THREAD

**Issue by RonBartsch** [Romanitho/Winget-AutoUpdate#663]
### The request

We chosen to not show any notifications for the users that an application is updated.
Now we created a modification for an application which verifies if the program is running.

In this scenario we would like to show a notification for the user that he or she should close the running application so that it can be updated.

In this issue an example is given but this does not work when notifications are completely disabled.
https://github.com/Romanitho/Winget-AutoUpdate/issues/302

### Is your feature request related to a problem?

```txt
Now I have added a wait if the application is running, but the whole auto update process hangs until this specific application is closed.
```

**Comment by AndrewDemski-ad-gmail-com** [comment]
Looks like a good candidate for a new task launched for interactive user - a core feature/ of the whole WAU.

P.S. I hope that your solution looks for all processes under given Installdir(s).
________________________________
From: RonBartsch ***@***.***>
Sent: 22 August 2024 09:21
To: Romanitho/Winget-AutoUpdate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Romanitho/Winget-AutoUpdate] [Feature Request]: Add "Mods"option to -NotificationLevel (Issue #663)


The request

We chosen to not show any notifications for the users that an application is updated.
Now we created a modification for an application which verifies if the program is running.

In this scenario we would like to show a notification for the user that he or she should close the running application so that it can be updated.

In this issue an example is given but this does not work when notifications are completely disabled.
#302<https://github.com/Romanitho/Winget-AutoUpdate/issues/302>

Is your feature request related to a problem?

Now I have added a wait if the application is running, but the whole auto update process hangs until this specific application is closed.

Additional information

No response

**Comment by Romanitho** [comment]
You could also add your own message box with a yes/no option. Due to ServiceUI.exe, your message will be seen by users even in the system context.
Example: https://woshub.com/popup-notification-powershell/
